### ISSUE TITLE
ReferenceError: DOMParser is not defined while using toJson

### ISSUE THREAD

**Issue by bijaykush** [rcasto/adaptive-html#7]
I am trying to convert html to adaptive json with as but getting error.

`var json = adpativeHtml.toJSON("<p>Turn me into an Adaptive Card</p>");`

Error: ReferenceError: DOMParser

@rcasto Any help on this?

**Comment by rcasto** [comment]
Not totes sure of your setup, but it should be working.

Below is a link to a CodePen that may be helpful:
[https://codepen.io/rcasto/pen/pojLYMJ?editors=0011](https://codepen.io/rcasto/pen/pojLYMJ?editors=0011)
